CREATE TABLE UTENTE(
ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
USERNAME,
PASSWORD,
EMAIL,
NOME,
COGNOME,
CF,
DATA_NASCITA,
LUOGO_DI_NASCITA,
INDIRIZZO,
SESSO
);

CREATE TABLE ESERCIZI(
ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
IMMAGINE
NOME
DESCRIZIONE
ESECUZIONE
CATEGORIA
);

CREATE TABLE ABBONAMENTO(
ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
COSTO
TIPOLOGIA
DURATA
NOME
DESCRIZIONE
);

CREATE TABLE CORSO(
ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
NOME
DESCRIZIONE
TIPOLOGIA
);

CREATE TABLE SLOT_PRENOTAZIONI(
ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
ORARIO_INIZIO
ORARIO_FINE
POSTI_DISPONIBILI
GIORNO
);

CREATE TABLE CATEGORIE_SCHEDA(
ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
NOME
DESCRIZIONE
);

CREATE TABLE CATEGORIA_ESERCIZI(
ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
NOME
DESCRIZIONE
);

CREATE TABLE PROVINCIA(
ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
NOME
);

CREATE TABLE REGIONE(
ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
NOME
);

CREATE TABLE CITTA(
ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
NOME
);

CREATE TABLE ISCRIZIONE(
ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
GIORNO
ORA_APERTURA
ORA_CHIUSURA
);

CREATE TABLE ORARI_PALESTRA(
ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE PERMESSI(
ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
RUOLI
PERMESSO
);




