CREATE database db_lightweight;
use db_lightwieght;

CREATE TABLE `UTENTE`(
`ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`USERNAME` varchar(255),
`PASSWORD` varchar(255),
`EMAIL` varchar(255),
`NOME` varchar(255),
`COGNOME` varchar(255),
`CF` varchar(16),
`DATA_NASCITA` date,
`LUOGO_DI_NASCITA` varchar(255),
`INDIRIZZO` varchar(255),
`SESSO` varchar(1)
);

CREATE TABLE `ESERCIZI`(
`ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`IMMAGINE` longblob,
`NOME` varchar(255),
`DESCRIZIONE` varchar(600),
`ESECUZIONE` varchar(255),
`CATEGORIA` tinyint
);

CREATE TABLE `ABBONAMENTO`(
`ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`COSTO` float,
`TIPOLOGIA` varchar(255),
`DURATA` varchar(255),
`NOME` varchar(255),
`DESCRIZIONE` varchar(255)
);

CREATE TABLE `CORSO`(
`ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`NOME` varchar(255),
`DESCRIZIONE` varchar(255),
`TIPOLOGIA` varchar(255)
);

CREATE TABLE `SLOT_PRENOTAZIONI`(
`ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`ORARIO_INIZIO` time,
`ORARIO_FINE` time,
`POSTI_DISPONIBILI` tinyint unsigned,
`GIORNO` varchar(255)
);

CREATE TABLE `CATEGORIE_SCHEDA`(
`ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`NOME` varchar(255),
`DESCRIZIONE` varchar(255)
);

CREATE TABLE `CATEGORIA_ESERCIZI`(
`ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`NOME` varchar(255),
`DESCRIZIONE` varchar(255)
);

CREATE TABLE `PROVINCIA`(
`ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`NOME` varchar(255)
);

CREATE TABLE `REGIONE`(
`ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`NOME` varchar(255)
);

CREATE TABLE `CITTA`(
`ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`NOME` varchar(255)
);

CREATE TABLE `ISCRIZIONE`(
`ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
# relazione con abbonamento e utente
);

CREATE TABLE `ORARI_PALESTRA`(
`ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`GIORNO` varchar(255),
`ORA_APERTURA` varchar(255),
`ORA_CHIUSURA` varchar(255)
);

CREATE TABLE `PERMESSI`(
`ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`RUOLI` varchar(255),
`PERMESSO` varchar(255)
);




